apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: client
        tier: application
        controller: supervisor.default.svc
    spec:
      containers:
      - image: registry2.applifier.info:5005/kontrol
        name: kontrol
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
