apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: supervisor
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: foo2
        tier: control
    spec:
      containers:
      - image: registry2.applifier.info:5005/kontrol
        name: kontrol
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: supervisor
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: foo2
    tier: control