apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  kontrol
    spec:
      containers:
      - name: kontrol
        image: test:latest
        imagePullPolicy: Never
        ports:
        - protocol:       TCP 
          containerPort:  8000

---

apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: kontrol