#!/usr/bin/python

import os
import sys
import json
import requests

if __name__ == '__main__':

    #
    # - fetch the current pod snapshot ($POD) and user data attached to this
    #   cluster ($STATUS)
    # - both are serialized json
    #
    pods = json.loads(os.environ['PODS'])
    status = json.loads(os.environ['STATUS']) if 'STATUS' in os.environ else {}

    for pod in pods:

        #
        # - for each pod in our latest snapshot issue a PUT /action/checkup to
        #   evaluate the 'checkup' script
        #
        try:
            url = 'http://%s:8000/action/checkup' % pod['ip']
            response = requests.put(url, timeout=5.0)
            print >> sys.stderr, 'HTTP %d <- POST /update %s' % (response.status_code, url)
            response.raise_for_status()
            status[pod['ip']] = response.text
        
        except Exception:
            pass
    #
    # - commit back the overall status by writing it back as serialized json
    #   to stdout
    #
    print json.dumps(status)